### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by OlivierShi** [iamsimha/dlsys-course-solutions#1]
hello, iamsimha:
    there is a problem with your logistic_regression.py, when i augment num_points to about 300, the results turns out infinite and NaN which is so strange. 
    likewise, my program has the same problem. the most simple case linear_regression.py in  https://github.com/OliveirShi/assignment1 .

**Comment by iamsimha** [comment]
is the learning rate high? did you try with a low learning rate?

**Comment by OlivierShi** [comment]
learning rate is set 0.01 same as yours. Exactly i have run your program many times, and the problem always exists as i said before.
In addition, i think you should recheck function gradient in MatMulOp(). When testing as following example, 
y = ad.matmul_op(x2, x3, False, True)  
x2_val = np.array([[1, 2], [3, 4], [5, 6]])  # (3, 2)
x3_val = np.array([[1, 2], [3, 4], [5, 6]])  # (3, 2)
there are some bugs during computing gradients.

**Comment by iamsimha** [comment]
If the learning rate is  0.001 and num_points is  300, then you would not get Nan. This is because for more number of points gradients sum up and hence there is gradient explosion. This could be avoided if we use SGD with certain batch size.

**Comment by OlivierShi** [comment]
I see, thank you very much. I thought the problem is associated with program in autodiff.py 
thanks again
